/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianyue_common_FileDescriptorPath */

#ifndef _Included_com_qianyue_common_FileDescriptorPath
#define _Included_com_qianyue_common_FileDescriptorPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qianyue_common_FileDescriptorPath
 * Method:    getPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qianyue_common_FileDescriptorPath_getPath
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
