/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qianyue_common_FileDescriptorPath */
#include <unistd.h>
#include <stdio.h>
#include "com_qianyue_common_FileDescriptorPath.h"

#define F_LEN 1024

JNIEXPORT jstring JNICALL Java_com_qianyue_common_FileDescriptorPath_getPath
        (JNIEnv *env, jclass thiz, jint fd) {
    char filename[F_LEN] = "temp";
    char buf[F_LEN];
    snprintf(filename, F_LEN, "/proc/%ld/fd/%d", (long) getpid(), fd);
    readlink(filename, buf, F_LEN);
    return (*env)->NewStringUTF(env, buf);
};